# Generated by Django 4.0.3 on 2022-07-21 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0011_alter_department_code_alter_emailrecord_email_id_and_more'),
        ('feedback', '0008_facultyvoting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='course',
        ),
        migrations.AddField(
            model_name='feedback',
            name='courses',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal.course'),
        ),
    ]
