# Generated by Django 4.0.3 on 2022-05-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0010_alter_emailrecord_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='emailrecord',
            name='email_id',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='emailrecord',
            name='enrollment_no',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='staffrecord',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
